name: taaruf-backend
on:
  push:
    branches: [main]
jobs:
  Deploy_to_GAE:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Load Config Files
        run: |
          echo "${{secrets.GAE_CONFIG}}" | base64 --decode > ../../actions/config/gae.env 
          echo "${{secrets.GCP_SA_KEY}}" > ../../actions/config/airy-adapter-349208-4c7f09b5f7c6.json

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm install

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          project_id: ${{secrets.GCP_PROJECT}}
          service_account_key: ${{secrets.GCP_SA_KEY}}

      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.8.0
        with:
          deliverables: ../../app.yaml
          project_id: ${{secrets.GCP_PROJECT}}
          credentials: ${{secrets.GCP_SA_KEY}}
          promote: true
          version: v1
